export const AppConstants = {
  SESSION_NAME_MAX_LENGTH: 30,
  AUDIO_SAMPLE_RATE: 16000,
  AUDIO_NUM_CHANNELS: 1,
  WORDS_PER_PARAGRAPH: 30,
  SENTENCES_PER_PARAGRAPH: 3,
  APP_BAR_HEIGHT: 60,
  RECORDING_CONTROLS_HEIGHT: 96,
  SMART_SPLIT_LONG_PAUSE_MS: 3000,
  SMART_SPLIT_MAX_ITEM_MS: 60000,
  SMART_SPLIT_SILENCE_ENERGY_THRESHOLD: 0.02,
} as const;
