export const AppConstants = {
  SESSION_NAME_MAX_LENGTH: 30,
  AUDIO_SAMPLE_RATE: 16000,
  AUDIO_BIT_RATE: 128000,
  AUDIO_NUM_CHANNELS: 1,
  AUDIO_ENCODER: 'wav' as const,
  WORDS_PER_PARAGRAPH: 30,
  SENTENCES_PER_PARAGRAPH: 3,
} as const;
