/** @type {import('jest').Config} */
module.exports = {
  preset: "jest-expo",
  setupFilesAfterEnv: ["./jest.setup.js"],
  transformIgnorePatterns: [
    "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@sentry/react-native|native-base|react-native-svg|react-native-reanimated|react-native-gesture-handler|react-native-screens|react-native-safe-area-context|@shopify/react-native-skia|react-native-aes-gcm-crypto|react-native-fs|@dr.pogodin/react-native-fs|react-native-logs|react-native-worklets|@supersami/rn-foreground-service|@react-native-async-storage/async-storage|@react-native-masked-view/masked-view|@react-native-community/.*|base64-js|zustand|immer|i18next|react-i18next)",
  ],
  moduleNameMapper: {
    "\\.svg$": "<rootDir>/__mocks__/svgMock.js",
    "\\.bin$": "<rootDir>/__mocks__/binMock.js",
    "\\.onnx$": "<rootDir>/__mocks__/binMock.js",
    "\\.(txt|wav)$": "<rootDir>/__mocks__/binMock.js",
    // .sql files are inlined via babel-plugin-inline-import in metro/builds;
    // jest doesn't run that transform, so map them to a no-op string.
    "\\.sql$": "<rootDir>/__mocks__/binMock.js",
    "^@/assets/(.*)$": "<rootDir>/assets/$1",
    "^@/(.*)$": "<rootDir>/src/$1",
    "^@modules/(.*)$": "<rootDir>/modules/$1",
  },
  testPathIgnorePatterns: [
    "/node_modules/",
    "<rootDir>/app/\\(dev\\)/design-system/",
    "<rootDir>/.build/",
  ],
  collectCoverageFrom: [
    "app/**/*.{ts,tsx}",
    "!app/\\(dev\\)/**",
    "src/components/**/*.{ts,tsx}",
    "src/constants/**/*.{ts,tsx}",
    "src/db/**/*.{ts,tsx}",
    "src/hooks/**/*.{ts,tsx}",
    "src/models/**/*.{ts,tsx}",
    "src/services/**/*.{ts,tsx}",
    "src/stores/**/*.{ts,tsx}",
    "src/theme/**/*.{ts,tsx}",
    "src/utils/**/*.{ts,tsx}",
    "!**/*.test.{ts,tsx}",
    "!**/*.gallery.{ts,tsx}",
    "!**/index.{ts,tsx}",
    "!**/__mocks__/**",
    "!**/node_modules/**",
    "!src/components/ui/icon/flagIcons.ts",
    "!src/components/shared/recording-controls/ThreeWaveLines.tsx",
    "!src/services/background-recording-service/BackgroundRecordingService.ts",
    "!src/services/model-download-service/ModelDownloadService.ts",
    "!src/services/sherpa-transcription-service/SherpaTranscriptionService.ts",
    "!src/stores/model-download-store/modelDownloadStore.ts",
    "!src/models/model-type/ModelType.ts",
    "!src/models/transcription-state/TranscriptionState.ts",
    "!src/db/migrations/**",
    "!src/db/schema.ts",
  ],
  coverageThreshold: {
    global: {
      branches: 90,
      functions: 95,
      lines: 95,
      statements: 95,
    },
  },
  modulePathIgnorePatterns: ["<rootDir>/.yoyo/"],
  clearMocks: true,
};
