import { useMemo } from "react";
import { useTranslation } from "react-i18next";

export const useLocalization = () => {
  const { t } = useTranslation();

  // Memoized: ~150 t() calls per render otherwise; t changes on language change.
  const loc = useMemo(
    () => ({
      sessionRenameTitle: t("sessionRenameTitle"),
      delete: t("delete"),
      modifiedPrefix: t("modifiedPrefix"),
      createdPrefix: t("createdPrefix"),
      save: t("save"),
      cancel: t("cancel"),
      edit: t("edit"),
      share: t("share"),
      rename: t("rename"),
      copy: t("copy"),
      merge: t("merge"),
      selectedCount: (count: number) => t("selectedCount", { count }),
      sessionNameLabel: t("sessionNameLabel"),
      sessionNameMaxLengthHelper: t("sessionNameMaxLengthHelper"),
      homeDeleteSelectedSessionsTitle: t("homeDeleteSelectedSessionsTitle"),
      homeDeleteSelectedSessionsMessage: (count: number) =>
        t("homeDeleteSelectedSessionsMessage", { count }),
      homeSessionsDeleted: (count: number) =>
        t("homeSessionsDeleted", { count }),
      transcriptionCount: (count: number) => t("transcriptionCount", { count }),
      sessionCount: (count: number) => t("sessionCount", { count }),
      homeFolder: t("homeFolder"),
      homeUpload: t("homeUpload"),
      uploadBusy: t("uploadBusy"),
      uploadFailed: (count: number) => t("uploadFailed", { count }),
      uploadErrorUnsupported: t("uploadErrorUnsupported"),
      uploadErrorTooLong: t("uploadErrorTooLong"),
      uploadErrorTooLarge: t("uploadErrorTooLarge"),
      uploadErrorEmpty: t("uploadErrorEmpty"),
      uploadErrorNoSpeech: t("uploadErrorNoSpeech"),
      uploadErrorFailed: t("uploadErrorFailed"),
      homeNewFolder: t("homeNewFolder"),
      folderMoreOptions: t("folderMoreOptions"),
      folderCreateTitle: t("folderCreateTitle"),
      folderNameLabel: t("folderNameLabel"),
      folderRenameTitle: t("folderRenameTitle"),
      folderDeleted: t("folderDeleted"),
      addToFolder: t("addToFolder"),
      selectFolder: t("selectFolder"),
      folderCreateAndAdd: t("folderCreateAndAdd"),
      sessionsAddedToFolder: (name: string) =>
        t("sessionsAddedToFolder", { name }),
      copyAsText: t("copyAsText"),
      downloadMarkdown: t("downloadMarkdown"),
      shareVia: t("shareVia"),
      markdownSaved: t("markdownSaved"),
      markdownSaveFailed: t("markdownSaveFailed"),
      folderDeleteWithSessionsTitle: (count: number) =>
        t("folderDeleteWithSessionsTitle", { count }),
      followUsOnX: t("followUs"),
      couldNotOpenLink: t("couldNotOpenLink"),
      incognitoModeTitle: t("incognitoModeTitle"),
      incognitoEmptyStateTitle: t("incognitoEmptyStateTitle"),
      incognitoEmptyStateDescription: t("incognitoEmptyStateDescription"),
      errorPrefix: t("errorPrefix"),
      recordingPrefix: t("recordingPrefix"),
      retry: t("retry"),
      emptySessionsMessage: t("emptySessionsMessage"),
      scrollToTop: t("scrollToTop"),
      scrollToLatest: t("scrollToLatest"),
      microphoneAccessRequiredTitle: t("microphoneAccessRequiredTitle"),
      microphoneAccessNeededMessage: t(
        "microphoneAccessRequiredMessageAndroid",
      ),
      microphoneAccessDeniedMessage: t("microphoneAccessDeniedMessage"),
      openSettings: t("openSettings"),
      homeFailedStartRecording: t("homeFailedStartRecording"),
      errorCreatingSessionTitle: t("errorCreatingSessionTitle"),
      copyFailedTitle: t("copyFailedTitle"),
      sessionDeleteTranscriptionsTitle: t("sessionDeleteTranscriptionsTitle"),
      sessionDeleteTranscriptionsMessage: (count: number) =>
        t("sessionDeleteTranscriptionsMessage", { count }),
      sessionTranscriptionsDeleted: (count: number) =>
        t("sessionTranscriptionsDeleted", { count }),
      sessionTranscriptionsMerged: (count: number) =>
        t("sessionTranscriptionsMerged", { count }),
      mergeFailedTitle: t("mergeFailedTitle"),
      allTranscriptionsCopied: t("allTranscriptionsCopied"),
      noTranscriptionsToCopy: t("noTranscriptionsToCopy"),
      copyFailed: (error: string) => t("copyFailed", { error }),
      shareFailed: (error: string) => t("shareFailed", { error }),
      sessionNotFound: t("sessionNotFound"),
      settingsTitle: t("settingsTitle"),
      title: t("title"),
      themeTitle: t("themeTitle"),
      textAppearanceTitle: t("textAppearanceTitle"),
      textAppearancePreview: t("textAppearancePreview"),
      fontSize: t("fontSize"),
      fontWeight: t("fontWeight"),
      boldText: t("boldText"),
      spokenLanguageTitle: t("spokenLanguageTitle"),
      spokenLanguageDescription: t("spokenLanguageDescription"),
      auto: t("auto"),
      light: t("light"),
      dark: t("dark"),
      description: t("description"),
      included: t("included"),
      downloaded: t("downloaded"),
      notDownloaded: t("notDownloaded"),
      downloading: t("downloading"),
      download: t("download"),
      deleteConfirmTitle: t("deleteConfirmTitle"),
      deleteConfirmMessage: t("deleteConfirmMessage"),
      downloadError: t("downloadError"),
      insufficientSpace: (required: string, available: string) =>
        t("insufficientSpace", { required, available }),
      languageCount: (count: number) => t("languageCount", { count }),
      transcriptionModeTitle: t("transcriptionModeTitle"),
      transcriptionSettings: t("transcriptionSettings"),
      close: t("close"),
      realtime: t("realtime"),
      highAccuracy: t("highAccuracy"),
      realtimeOnly: t("realtimeOnly"),
      highAccuracyOnly: t("highAccuracyOnly"),
      selected: t("selected"),
      errorStatus: t("errorStatus"),
      sectionDownloaded: t("sectionDownloaded"),
      sectionAvailable: t("sectionAvailable"),
      deletedToast: t("deletedToast"),
      downloadedToast: t("downloadedToast"),
      downloadFailed: t("downloadFailed"),
      tryAgain: t("tryAgain"),
      languagesTitle: t("languagesTitle"),
      languagesSupported: (count: number) => t("languagesSupported", { count }),
      recordingTooShort: t("recordingTooShort"),
      transcriptionFailed: t("transcriptionFailed"),
      failedToInitializeEngine: t("failedToInitializeEngine"),
      copiedToClipboard: t("copiedToClipboard"),
      contactSupport: t("contactSupport"),
      advancedSettingsTitle: t("advancedSettingsTitle"),
      smartSplitTitle: t("smartSplitTitle"),
      smartSplitDescription: t("smartSplitDescription"),
      keyboardAutocorrectTitle: t("keyboardAutocorrectTitle"),
      keyboardAutocorrectDescription: t("keyboardAutocorrectDescription"),
      keyboardHapticTitle: t("keyboardHapticTitle"),
      keyboardHapticDescription: t("keyboardHapticDescription"),
      keyboardSoundTitle: t("keyboardSoundTitle"),
      keyboardSoundDescription: t("keyboardSoundDescription"),
      micTimeoutTitle: t("micTimeoutTitle"),
      micTimeoutDescription: t("micTimeoutDescription"),
      micTimeoutOff: t("micTimeoutOff"),
      micTimeout1Min: t("micTimeout1Min"),
      micTimeout5Min: t("micTimeout5Min"),
      micTimeout20Min: t("micTimeout20Min"),
      micTimeout60Min: t("micTimeout60Min"),
      keyboardPromptTitle: t("keyboardPromptTitle"),
      keyboardPromptBody: t("keyboardPromptBody"),
      keyboardPromptCta: t("keyboardPromptCta"),
      keyboardPromptDismiss: t("keyboardPromptDismiss"),
      voiceSessionHintTitle: t("voiceSessionHintTitle"),
      voiceSessionHintBody: t("voiceSessionHintBody"),
      voiceSessionHintCta: t("voiceSessionHintCta"),
      largerModelSuggestionTitle: t("largerModelSuggestionTitle"),
      largerModelSuggestionBody: (language: string) =>
        t("largerModelSuggestionBody", { language }),
      largerModelSuggestionCta: t("largerModelSuggestionCta"),
      largerModelSuggestionDismiss: t("largerModelSuggestionDismiss"),
      advancedSettingsAddKeyboardTitle: t("advancedSettingsAddKeyboardTitle"),
      advancedSettingsAddKeyboardDescription: t(
        "advancedSettingsAddKeyboardDescription",
      ),
      welcomeTitle: t("welcomeTitle"),
      welcomeSubtitle: t("welcomeSubtitle"),
      welcomeGetStarted: t("welcomeGetStarted"),
      back: t("back"),
      onboardingSkip: t("onboardingSkip"),
      onboardingSkipConfirmTitle: t("onboardingSkipConfirmTitle"),
      onboardingSkipConfirmMessage: t("onboardingSkipConfirmMessage"),
      onboardingAllowMicrophoneTitle: t("onboardingAllowMicrophoneTitle"),
      onboardingAllow: t("onboardingAllow"),
      onboardingEnableKeyboardTitle: t("onboardingEnableKeyboardTitle"),
      onboardingEnableKeyboardTooltip: t("onboardingEnableKeyboardTooltip"),
      onboardingEnableKeyboardRowEchos: t("onboardingEnableKeyboardRowEchos"),
      onboardingEnableKeyboardRowFullAccess: t(
        "onboardingEnableKeyboardRowFullAccess",
      ),
      onboardingGoToSettings: t("onboardingGoToSettings"),
      onboardingSpokenLanguageTitle: t("onboardingSpokenLanguageTitle"),
      onboardingNext: t("onboardingNext"),
      onboardingTryLargerModelTitle: t("onboardingTryLargerModelTitle"),
      onboardingTryLargerModelSubtitle: t("onboardingTryLargerModelSubtitle"),
      onboardingNotNow: t("onboardingNotNow"),
      onboardingTutorialIntroTitle: t("onboardingTutorialIntroTitle"),
      onboardingTutorialIntroSubtitle: t("onboardingTutorialIntroSubtitle"),
      onboardingSwitchKeyboardTitle: t("onboardingSwitchKeyboardTitle"),
      onboardingSwitchKeyboardSubtitle: t("onboardingSwitchKeyboardSubtitle"),
      onboardingDictateTitle: t("onboardingDictateTitle"),
      onboardingDictateSubtitle: t("onboardingDictateSubtitle"),
      onboardingDictatePlaceholder: t("onboardingDictatePlaceholder"),
      onboardingAutocorrectTitle: t("onboardingAutocorrectTitle"),
      onboardingAutocorrectSubtitle: t("onboardingAutocorrectSubtitle"),
      onboardingRecordTitle: t("onboardingRecordTitle"),
      onboardingRecordSubtitle: t("onboardingRecordSubtitle"),
      onboardingTranscriptReadyTitle: t("onboardingTranscriptReadyTitle"),
      onboardingTranscriptReadySubtitle: t("onboardingTranscriptReadySubtitle"),
      onboardingPrivacyTitle: t("onboardingPrivacyTitle"),
      onboardingPrivacySubtitle: t("onboardingPrivacySubtitle"),
      onboardingAllSetTitle: t("onboardingAllSetTitle"),
      onboardingAllSetSubtitle: t("onboardingAllSetSubtitle"),
      settingsSectionTranscription: t("settingsSectionTranscription"),
      settingsSectionAppearance: t("settingsSectionAppearance"),
      biometricAuthTitle: t("biometricAuthTitle"),
      biometricAuthPrompt: t("biometricAuthPrompt"),
      biometricAuthUnlock: t("biometricAuthUnlock"),
      biometricAuthUnavailable: t("biometricAuthUnavailable"),
    }),
    [t],
  );

  return { t, loc };
};
