import { useTranslation } from "react-i18next";

export const useLocalization = () => {
  const { t } = useTranslation();

  return {
    t,
    loc: {
      sessionRenameTitle: t("sessionRenameTitle"),
      delete: t("delete"),
      modifiedPrefix: t("modifiedPrefix"),
      createdPrefix: t("createdPrefix"),
      save: t("save"),
      cancel: t("cancel"),
      edit: t("edit"),
      share: t("share"),
      rename: t("rename"),
      copy: t("copy"),
      selectedCount: (count: number) => t("selectedCount", { count }),
      sessionNameLabel: t("sessionNameLabel"),
      sessionNameMaxLengthHelper: t("sessionNameMaxLengthHelper"),
      homeDeleteSelectedSessionsTitle: t("homeDeleteSelectedSessionsTitle"),
      homeDeleteSelectedSessionsMessage: (count: number) =>
        t("homeDeleteSelectedSessionsMessage", { count }),
      homeSessionsDeleted: (count: number) =>
        t("homeSessionsDeleted", { count }),
      transcriptionCount: (count: number) => t("transcriptionCount", { count }),
      followUsOnX: t("followUs"),
      couldNotOpenLink: t("couldNotOpenLink"),
      incognitoModeTitle: t("incognitoModeTitle"),
      incognitoEmptyStateTitle: t("incognitoEmptyStateTitle"),
      incognitoEmptyStateDescription: t("incognitoEmptyStateDescription"),
      errorPrefix: t("errorPrefix"),
      recordingPrefix: t("recordingPrefix"),
      retry: t("retry"),
      emptySessionsMessage: t("emptySessionsMessage"),
      scrollToTop: t("scrollToTop"),
      scrollToLatest: t("scrollToLatest"),
      microphoneAccessRequiredTitle: t("microphoneAccessRequiredTitle"),
      microphoneAccessNeededMessage: t(
        "microphoneAccessRequiredMessageAndroid",
      ),
      microphoneAccessDeniedMessage: t("microphoneAccessDeniedMessage"),
      openSettings: t("openSettings"),
      homeFailedStartRecording: t("homeFailedStartRecording"),
      errorCreatingSessionTitle: t("errorCreatingSessionTitle"),
      copyFailedTitle: t("copyFailedTitle"),
      sessionDeleteTranscriptionsTitle: t("sessionDeleteTranscriptionsTitle"),
      sessionDeleteTranscriptionsMessage: (count: number) =>
        t("sessionDeleteTranscriptionsMessage", { count }),
      sessionTranscriptionsDeleted: (count: number) =>
        t("sessionTranscriptionsDeleted", { count }),
      allTranscriptionsCopied: t("allTranscriptionsCopied"),
      noTranscriptionsToCopy: t("noTranscriptionsToCopy"),
      copyFailed: (error: string) => t("copyFailed", { error }),
      shareFailed: (error: string) => t("shareFailed", { error }),
      sessionNotFound: t("sessionNotFound"),
      settingsTitle: t("settingsTitle"),
      title: t("title"),
      themeTitle: t("themeTitle"),
      spokenLanguageTitle: t("spokenLanguageTitle"),
      auto: t("auto"),
      light: t("light"),
      dark: t("dark"),
      description: t("description"),
      included: t("included"),
      downloaded: t("downloaded"),
      notDownloaded: t("notDownloaded"),
      downloading: t("downloading"),
      download: t("download"),
      deleteConfirmTitle: t("deleteConfirmTitle"),
      deleteConfirmMessage: t("deleteConfirmMessage"),
      downloadError: t("downloadError"),
      insufficientSpace: (required: string, available: string) =>
        t("insufficientSpace", { required, available }),
      languageCount: (count: number) => t("languageCount", { count }),
      realtime: t("realtime"),
      highAccuracy: t("highAccuracy"),
      realtimeOnly: t("realtimeOnly"),
      highAccuracyOnly: t("highAccuracyOnly"),
      selected: t("selected"),
      errorStatus: t("errorStatus"),
      sectionDownloaded: t("sectionDownloaded"),
      sectionAvailable: t("sectionAvailable"),
      deletedToast: t("deletedToast"),
      downloadedToast: t("downloadedToast"),
      downloadFailed: t("downloadFailed"),
      tryAgain: t("tryAgain"),
      languagesTitle: t("languagesTitle"),
      languagesSupported: (count: number) => t("languagesSupported", { count }),
      recordingTooShort: t("recordingTooShort"),
      transcriptionFailed: t("transcriptionFailed"),
      failedToInitializeEngine: t("failedToInitializeEngine"),
      copiedToClipboard: t("copiedToClipboard"),
      contactSupport: t("contactSupport"),
      advancedSettingsTitle: t("advancedSettingsTitle"),
      smartSplitTitle: t("smartSplitTitle"),
      smartSplitDescription: t("smartSplitDescription"),
      keyboardAutocorrectTitle: t("keyboardAutocorrectTitle"),
      keyboardAutocorrectDescription: t("keyboardAutocorrectDescription"),
      keyboardPromptTitle: t("keyboardPromptTitle"),
      keyboardPromptBody: t("keyboardPromptBody"),
      keyboardPromptIosDisclaimer: t("keyboardPromptIosDisclaimer"),
      keyboardPromptCta: t("keyboardPromptCta"),
      keyboardPromptDismiss: t("keyboardPromptDismiss"),
      advancedSettingsAddKeyboardTitle: t("advancedSettingsAddKeyboardTitle"),
      advancedSettingsAddKeyboardDescription: t(
        "advancedSettingsAddKeyboardDescription",
      ),
    },
  };
};
