const { withDangerousMod, withAppDelegate } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

const TEMPLATES_DIR = path.join(__dirname, "templates");

/**
 * Writes SherpaBridge (ObjC++), KeyboardTranscriptionListener (Swift), and the
 * bridging header into the main app directory, and injects listener startup
 * into AppDelegate.
 *
 * NOTE: The Xcode project setup (adding files to build phases, setting the
 * bridging header and sherpa-onnx header search paths) is done by
 * setupListenerInXcodeProject(), which must be called from
 * withIosKeyboardExtension's withXcodeProject callback so a single pass
 * handles all Xcode project mutations.
 */
function withIosTranscriptionListener(config) {
  config = withListenerFiles(config);
  config = withListenerStartup(config);
  return config;
}

/**
 * Writes the source files into the main app directory.
 */
function withListenerFiles(config) {
  return withDangerousMod(config, [
    "ios",
    (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const projectName = config.modRequest.projectName || "Echos";
      const mainAppDir = path.join(projectRoot, "ios", projectName);

      const filesToCopy = [
        "KeyboardTranscriptionListener.swift",
        "SherpaBridge.h",
        "SherpaBridge.mm",
      ];

      for (const file of filesToCopy) {
        const templatePath = path.join(TEMPLATES_DIR, file);
        if (fs.existsSync(templatePath)) {
          fs.writeFileSync(
            path.join(mainAppDir, file),
            fs.readFileSync(templatePath, "utf8"),
          );
        }
      }

      // Bridging header so Swift can see SherpaBridge.
      const bridgingHeader = `//
// Echos-Bridging-Header.h
// Auto-generated by withEchosKeyboard config plugin.
//

#import "SherpaBridge.h"
`;
      fs.writeFileSync(
        path.join(mainAppDir, "Echos-Bridging-Header.h"),
        bridgingHeader,
      );

      return config;
    },
  ]);
}

/**
 * Called from withIosKeyboardExtension's withXcodeProject callback.
 * Adds SherpaBridge and listener files to the main app target's Sources build
 * phase, sets the bridging header build setting, and injects the sherpa-onnx
 * xcframework header search paths.
 *
 * @param {object} proj - The xcode project object (config.modResults)
 * @param {string} projectName - The project name (e.g., "Echos")
 */
function setupListenerInXcodeProject(proj, projectName) {
  const mainTarget = proj.getFirstTarget();
  if (!mainTarget) return;

  // getFirstTarget() returns { uuid: "...", firstTarget: { ...target object } }
  // The uuid is the KEY in PBXNativeTarget, firstTarget is the target object itself
  const mainTargetUuid = mainTarget.uuid;

  // Find the main app group
  const groups = proj.hash.project.objects["PBXGroup"];
  const mainGroupKey = proj.getFirstProject().firstProject.mainGroup;
  let appGroupKey = null;
  const mainGroup = groups[mainGroupKey];
  if (mainGroup && mainGroup.children) {
    for (const child of mainGroup.children) {
      const g = groups[child.value];
      if (g && (g.name === projectName || g.path === projectName)) {
        appGroupKey = child.value;
        break;
      }
    }
  }

  const fileRefSection = proj.hash.project.objects["PBXFileReference"];
  const buildFileSection = proj.hash.project.objects["PBXBuildFile"];

  // Create file references
  const files = [
    {
      name: "SherpaBridge.h",
      type: "sourcecode.c.h",
      compile: false,
    },
    {
      name: "SherpaBridge.mm",
      type: "sourcecode.cpp.objcpp",
      compile: true,
    },
    {
      name: "Echos-Bridging-Header.h",
      type: "sourcecode.c.h",
      compile: false,
    },
    {
      name: "KeyboardTranscriptionListener.swift",
      type: "sourcecode.swift",
      compile: true,
    },
  ];

  const buildFileUuids = [];

  for (const file of files) {
    const refUuid = proj.generateUuid();
    fileRefSection[refUuid] = {
      isa: "PBXFileReference",
      lastKnownFileType: file.type,
      name: file.name,
      path: `${projectName}/${file.name}`,
      sourceTree: '"<group>"',
    };
    fileRefSection[`${refUuid}_comment`] = file.name;

    // Add to app group
    if (appGroupKey && groups[appGroupKey]) {
      groups[appGroupKey].children.push({
        value: refUuid,
        comment: file.name,
      });
    }

    // Create build file entry for compilable files
    if (file.compile) {
      const buildFileUuid = proj.generateUuid();
      buildFileSection[buildFileUuid] = {
        isa: "PBXBuildFile",
        fileRef: refUuid,
      };
      buildFileSection[`${buildFileUuid}_comment`] = `${file.name} in Sources`;
      buildFileUuids.push({
        value: buildFileUuid,
        comment: `${file.name} in Sources`,
      });
    }
  }

  // Add compilable files to the main target's Sources build phase
  const nativeTargets = proj.hash.project.objects["PBXNativeTarget"];
  const targetObj = nativeTargets[mainTargetUuid];
  if (targetObj) {
    const sourcePhases = proj.hash.project.objects["PBXSourcesBuildPhase"];
    for (const bp of targetObj.buildPhases) {
      const bpUuid = bp.value || bp;
      if (sourcePhases[bpUuid]) {
        sourcePhases[bpUuid].files.push(...buildFileUuids);
        break;
      }
    }
  }

  // Set bridging header + sherpa-onnx header search paths on the main app
  // target. The SherpaOnnx pod exposes its C++ API headers via
  // `pod_target_xcconfig.HEADER_SEARCH_PATHS` (pod-only), so the main app
  // target can't resolve `#include <sherpa-onnx/c-api/cxx-api.h>` unless we
  // mirror the search paths here.
  const xcframeworkHeaders =
    "$(PROJECT_DIR)/../node_modules/react-native-sherpa-onnx/ios/Frameworks/sherpa_onnx.xcframework";
  const sherpaHeaderPaths = [
    `"${xcframeworkHeaders}/ios-arm64/Headers"`,
    `"${xcframeworkHeaders}/ios-arm64_x86_64-simulator/Headers"`,
  ];

  const configurations = proj.pbxXCBuildConfigurationSection();
  for (const key in configurations) {
    const c = configurations[key];
    if (!c.buildSettings) continue;
    const bid = (c.buildSettings.PRODUCT_BUNDLE_IDENTIFIER || "").replace(
      /^"|"$/g,
      "",
    );
    if (bid === "com.a1lab.echos") {
      c.buildSettings.SWIFT_OBJC_BRIDGING_HEADER = `"${projectName}/Echos-Bridging-Header.h"`;

      // pbxproj array entries must be quoted when they contain `$`, `(`, or
      // `)` — otherwise the CocoaPods-side nanaimo parser rejects the file
      // with "Array missing ',' in between objects". Normalize every entry
      // to the `"..."` form to match the rest of this plugin (see the
      // `TARGETED_DEVICE_FAMILY = '"1,2"'` convention above).
      const ensureQuoted = (s) => (s.startsWith('"') ? s : `"${s}"`);
      const existing = c.buildSettings.HEADER_SEARCH_PATHS;
      const existingList = Array.isArray(existing)
        ? existing.map(ensureQuoted)
        : existing
          ? [ensureQuoted(existing)]
          : ['"$(inherited)"'];
      for (const p of sherpaHeaderPaths) {
        if (!existingList.includes(p)) existingList.push(p);
      }
      c.buildSettings.HEADER_SEARCH_PATHS = existingList;
    }
  }
}

/**
 * Injects KeyboardTranscriptionListener.shared.startListening() into AppDelegate.
 */
function withListenerStartup(config) {
  return withAppDelegate(config, (config) => {
    let contents = config.modResults.contents;

    if (contents.includes("KeyboardTranscriptionListener")) {
      return config;
    }

    if (contents.includes("ExpoAppDelegate")) {
      const marker = "override func application(";
      const markerIdx = contents.indexOf(marker);
      if (markerIdx !== -1) {
        const braceIdx = contents.indexOf("{", markerIdx);
        if (braceIdx !== -1) {
          const nextLineIdx = contents.indexOf("\n", braceIdx);
          if (nextLineIdx !== -1) {
            const injection = `
    // Start keyboard transcription listener
    KeyboardTranscriptionListener.shared.startListening()
`;
            contents =
              contents.slice(0, nextLineIdx + 1) +
              injection +
              contents.slice(nextLineIdx + 1);
          }
        }
      }
    }

    config.modResults.contents = contents;
    return config;
  });
}

module.exports = { withIosTranscriptionListener, setupListenerInXcodeProject };
