apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'com.a1lab.echos.audiodecoder'
version = '0.0.1'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()

android {
  namespace "com.a1lab.echos.audiodecoder"
  compileSdkVersion safeExtGet("compileSdkVersion", 35)

  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 26)
    targetSdkVersion safeExtGet("targetSdkVersion", 34)
  }
}

